# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SolidPy',
                'doc_host': 'https://Bullish-Design.github.io',
                'git_url': 'https://github.com/Bullish-Design/SolidPy',
                'lib_path': 'SolidPy'},
  'syms': {'SolidPy.core': {'SolidPy.core.foo': ('core.html#foo', 'SolidPy/core.py')}}}
