# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_drawingdoc.ipynb.

# %% auto 0
__all__ = ['DrawingDoc']

# %% ../nbs/07_drawingdoc.ipynb 1
from .modeldoc import ModelDoc
from .interfaces.idrawingdoc import IDrawingDoc


class DrawingDoc(IDrawingDoc, ModelDoc):
    def __init__(self, system_object):
        super().__init__(system_object)

