# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_featuremanager.ipynb.

# %% auto 0
__all__ = ['FeatureManager']

# %% ../nbs/05_featuremanager.ipynb 1
import win32com.client
import pythoncom

from .interfaces.ifeaturemanager import IFeatureManager
from .feature import Feature


class FeatureManager(IFeatureManager):
    def __init__(self, parent):
        super().__init__(parent)

    def get_features(self, top_level_only=True):
        return [
            Feature(system_object)
            for system_object in self._get_features(top_level_only)
        ]

