# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_modeldocextension.ipynb.

# %% auto 0
__all__ = ['ModelDocExtension']

# %% ../nbs/03_modeldocextension.ipynb 1
import win32com.client

from .interfaces.imodeldocextension import IModelDocExtension


class ModelDocExtension(IModelDocExtension):
    def __init__(self, parent):
        super().__init__(parent)

